### ISSUE TITLE
显示  正在登陆... 然后报错了

### ISSUE THREAD

**Issue by Kegekkk** [Mr-Gump/iCourse_so_easy#3]
Traceback (most recent call last):
  File "C:\Download\moocV4.0\moocV4.0.py", line 252, in <module>
    test.login(chrome_driver)
  File "C:\Download\moocV4.0\moocV4.0.py", line 84, in login
    button2 = chrome_driver.find_element_by_class_name("tab0")
  File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tab0"}
  (Session info: chrome=81.0.4044.113)

**Comment by Mr-Gump** [comment]
十分抱歉和惭愧，这个issue我很早就知道了。原因在于网易在登录页面增加了一个内联框架，但由于时间原因一直没有更改这个bug，谢谢你的指出，我会尽快修改的！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kege"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上10:02
收件人:&nbsp;"Mr-Gump/iCourse_so_easy"<iCourse_so_easy@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Mr-Gump/iCourse_so_easy] 显示  正在登陆... 然后报错了 (#3)





 
Traceback (most recent call last):
 File "C:\Download\moocV4.0\moocV4.0.py", line 252, in 
 test.login(chrome_driver)
 File "C:\Download\moocV4.0\moocV4.0.py", line 84, in login
 button2 = chrome_driver.find_element_by_class_name("tab0")
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
 return self.find_element(by=By.CLASS_NAME, value=name)
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
 return self.execute(Command.FIND_ELEMENT, {
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
 self.error_handler.check_response(response)
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tab0"}
 (Session info: chrome=81.0.4044.113)

**Comment by Mr-Gump** [comment]
已经修改好了，可以正常使用了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kege"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 晚上10:02
收件人:&nbsp;"Mr-Gump/iCourse_so_easy"<iCourse_so_easy@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Mr-Gump/iCourse_so_easy] 显示  正在登陆... 然后报错了 (#3)





 
Traceback (most recent call last):
 File "C:\Download\moocV4.0\moocV4.0.py", line 252, in 
 test.login(chrome_driver)
 File "C:\Download\moocV4.0\moocV4.0.py", line 84, in login
 button2 = chrome_driver.find_element_by_class_name("tab0")
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
 return self.find_element(by=By.CLASS_NAME, value=name)
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
 return self.execute(Command.FIND_ELEMENT, {
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
 self.error_handler.check_response(response)
 File "C:\Users\Kege\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".tab0"}
 (Session info: chrome=81.0.4044.113)
